### ISSUE TITLE
Survey for Assignment/Project option

### ISSUE THREAD

**Issue by 20AHA** [CISC-873/Information#3]
Has the survey for deciding whether we want assignment or project grading for the course been uploaded? If yes, where's it?

**Comment by steven-hh-ding** [comment]
voila: https://docs.google.com/forms/d/e/1FAIpQLSffnmeNGvrFgSY3-WfzR98qLnOZWJGXBCW2dY6LuKgVoly7yQ/viewform?usp=sf_link 

sorry for the delays!!
