### ISSUE TITLE
Recommended code / documentation structure (Assignment 0)

### ISSUE THREAD

**Issue by ColtonBarr** [CISC-873/Information#5]
Hi Professor -

I'm just wondering how you would suggest we structure our code to keep track of the different models and model variants. Should we complete the full assignment in one jupyter notebook with separate sections for each model / model variant? Or would you recommend a separate notebook for each model?

I also wanted to clarify whether documentation of the code and answering of questions directly within the jupyter notebook(s) is sufficient, or if we should have a separate .pdf for documentation / answers.

I appreciate your help (and any suggestions from classmates)!!

**Comment by steven-hh-ding** [comment]
@ColtonBarr  Thanks for the question! It will be great if everything is in a single PDF (easier for us..) but you can separate them into different sections. For the answers, if you use jupyter notebook, you can add a text/markdown sections as well.

**Comment by ColtonBarr** [comment]
Ok great, that makes things easier to document. Thank you!
